import { translate } from '@/plugins/i18n.plugin';

// From https://datatracker.ietf.org/doc/html/rfc7518#section-3.1
export const ALGORITHM_DESCRIPTIONS: { [k: string]: string } = {
  HS256: translate('tools.jwt-parser.algorithms.hs256'),
  HS384: translate('tools.jwt-parser.algorithms.hs384'),
  HS512: translate('tools.jwt-parser.algorithms.hs512'),
  RS256: translate('tools.jwt-parser.algorithms.rs256'),
  RS384: translate('tools.jwt-parser.algorithms.rs384'),
  RS512: translate('tools.jwt-parser.algorithms.rs512'),
  ES256: translate('tools.jwt-parser.algorithms.es256'),
  ES384: translate('tools.jwt-parser.algorithms.es384'),
  ES512: translate('tools.jwt-parser.algorithms.es512'),
  PS256: translate('tools.jwt-parser.algorithms.ps256'),
  PS384: translate('tools.jwt-parser.algorithms.ps384'),
  PS512: translate('tools.jwt-parser.algorithms.ps512'),
  none: translate('tools.jwt-parser.algorithms.none'),
};

// List extracted from IANA: https://www.iana.org/assignments/jwt/jwt.xhtml
export const CLAIM_DESCRIPTIONS: Record<string, string> = {
  typ: translate('tools.jwt-parser.claims.typ'),
  alg: translate('tools.jwt-parser.claims.alg'),
  iss: translate('tools.jwt-parser.claims.iss'),
  sub: translate('tools.jwt-parser.claims.sub'),
  aud: translate('tools.jwt-parser.claims.aud'),
  exp: translate('tools.jwt-parser.claims.exp'),
  nbf: translate('tools.jwt-parser.claims.nbf'),
  iat: translate('tools.jwt-parser.claims.iat'),
  jti: translate('tools.jwt-parser.claims.jti'),
  name: translate('tools.jwt-parser.claims.name'),
  given_name: translate('tools.jwt-parser.claims.given_name'),
  family_name: translate('tools.jwt-parser.claims.family_name'),
  middle_name: translate('tools.jwt-parser.claims.middle_name'),
  nickname: translate('tools.jwt-parser.claims.nickname'),
  preferred_username: translate('tools.jwt-parser.claims.preferred_username'),
  profile: translate('tools.jwt-parser.claims.profile'),
  picture: translate('tools.jwt-parser.claims.picture'),
  website: translate('tools.jwt-parser.claims.website'),
  email: translate('tools.jwt-parser.claims.email'),
  email_verified: translate('tools.jwt-parser.claims.email_verified'),
  gender: translate('tools.jwt-parser.claims.gender'),
  birthdate: translate('tools.jwt-parser.claims.birthdate'),
  zoneinfo: translate('tools.jwt-parser.claims.zoneinfo'),
  locale: translate('tools.jwt-parser.claims.locale'),
  phone_number: translate('tools.jwt-parser.claims.phone_number'),
  phone_number_verified: translate('tools.jwt-parser.claims.phone_number_verified'),
  address: translate('tools.jwt-parser.claims.address'),
  updated_at: translate('tools.jwt-parser.claims.updated_at'),
  azp: translate('tools.jwt-parser.claims.azp'),
  nonce: translate('tools.jwt-parser.claims.nonce'),
  auth_time: translate('tools.jwt-parser.claims.auth_time'),
  at_hash: translate('tools.jwt-parser.claims.at_hash'),
  c_hash: translate('tools.jwt-parser.claims.c_hash'),
  acr: translate('tools.jwt-parser.claims.acr'),
  amr: translate('tools.jwt-parser.claims.amr'),
  sub_jwk: translate('tools.jwt-parser.claims.sub_jwk'),
  cnf: translate('tools.jwt-parser.claims.cnf'),
  sip_from_tag: translate('tools.jwt-parser.claims.sip_from_tag'),
  sip_date: translate('tools.jwt-parser.claims.sip_date'),
  sip_callid: translate('tools.jwt-parser.claims.sip_callid'),
  sip_cseq_num: translate('tools.jwt-parser.claims.sip_cseq_num'),
  sip_via_branch: translate('tools.jwt-parser.claims.sip_via_branch'),
  orig: translate('tools.jwt-parser.claims.orig'),
  dest: translate('tools.jwt-parser.claims.dest'),
  mky: translate('tools.jwt-parser.claims.mky'),
  events: translate('tools.jwt-parser.claims.events'),
  toe: translate('tools.jwt-parser.claims.toe'),
  txn: translate('tools.jwt-parser.claims.txn'),
  rph: translate('tools.jwt-parser.claims.rph'),
  sid: translate('tools.jwt-parser.claims.sid'),
  vot: translate('tools.jwt-parser.claims.vot'),
  vtm: translate('tools.jwt-parser.claims.vtm'),
  attest: translate('tools.jwt-parser.claims.attest'),
  origid: translate('tools.jwt-parser.claims.origid'),
  act: translate('tools.jwt-parser.claims.act'),
  scope: translate('tools.jwt-parser.claims.scope'),
  client_id: translate('tools.jwt-parser.claims.client_id'),
  may_act: translate('tools.jwt-parser.claims.may_act'),
  jcard: translate('tools.jwt-parser.claims.jcard'),
  at_use_nbr: translate('tools.jwt-parser.claims.at_use_nbr'),
  div: translate('tools.jwt-parser.claims.div'),
  opt: translate('tools.jwt-parser.claims.opt'),
  vc: translate('tools.jwt-parser.claims.vc'),
  vp: translate('tools.jwt-parser.claims.vp'),
  sph: translate('tools.jwt-parser.claims.sph'),
  ace_profile: translate('tools.jwt-parser.claims.ace_profile'),
  cnonce: translate('tools.jwt-parser.claims.cnonce'),
  exi: translate('tools.jwt-parser.claims.exi'),
  roles: translate('tools.jwt-parser.claims.roles'),
  groups: translate('tools.jwt-parser.claims.groups'),
  entitlements: translate('tools.jwt-parser.claims.entitlements'),
  token_introspection: translate('tools.jwt-parser.claims.token_introspection'),
};
